=== Jossie7/Examen_UD4/Ejercicio1/pedido.dtd
<!ELEMENT empresa (sucursales*)>
<!ELEMENT sucursales (sucursal*)>
<!ATTLIST sucursales pais CDATA #REQUIRED>
<!ELEMENT sucursal (nombre,zonaExposicion*, zonaGestion*,pedido*)>
<!ATTLIST sucursal codigo CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT zonaExposicion (ubicacion,Recibe)>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT Recibe (#PCDATA)>
<!ELEMENT zonaGestion (ubicación,recibe)>
<!ELEMENT ubicación (#PCDATA)>
<!ELEMENT recibe (#PCDATA)>
<!ELEMENT pedido (direccionesEnvio*,trabajadorEncargado,fecha,Observaciones,articulos*)>
<!ELEMENT direccionesEnvio (direccion1,direccion2)>
<!ELEMENT direccion1 (#PCDATA)>
<!ELEMENT direccion2 (#PCDATA)>
<!ELEMENT trabajadorEncargado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT Observaciones (#PCDATA)>
<!ELEMENT articulos (unidadesPedidas,precio, observaciones,plazoRevision)>
<!ELEMENT unidadesPedidas (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT plazoRevision (#PCDATA)>
<!ATTLIST articulos Código CDATA #REQUIRED>

=== Jossie7/Examen_UD4/Ejercicio1/pedido.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "pedido.dtd">
<empresa>
    <sucursales pais="España">
        <sucursal codigo = "A1234567">
            <nombre>central</nombre>
            <zonaExposicion>
                <ubicacion> </ubicacion>
                <Recibe> artículos </Recibe>
            </zonaExposicion>
            <zonaGestion>
                <ubicación> </ubicación>
                <recibe> albarán y pago</recibe>
            </zonaGestion>
            <pedido>
                <direccionesEnvio>
                    <direccion1> </direccion1>
                    <direccion2> </direccion2>
                </direccionesEnvio>
                <trabajadorEncargado> Pepito Perez</trabajadorEncargado>
                <fecha> 2021-02-02 </fecha>
                <Observaciones> urgente </Observaciones>
                <articulos Código="ABC-123">
                    <unidadesPedidas> 10</unidadesPedidas>
                    <precio> 10.63 </precio>
                    <observaciones> En buen estado </observaciones>
                    <plazoRevision> 10 </plazoRevision>
                </articulos>
            </pedido>
    </sucursal>
    </sucursales>
</empresa>
